name: CI

# Run this workflow every time a commit is pushed to main or a pull request is opened against main
on: push

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/${{ secrets.ORGANIZATION_NAME }}/${{ secrets.PROJECT_NAME }}
            azure-pipeline-name: ${{ PIPELINE_NAME }}
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
